version: '3'

services:
  redis-server:
    image: redis
    container_name: redis-server
    command: redis-server --port 6379
    hostname: redis
    environment:
      TZ: Asia/Seoul
    ports:
      - "6378:6379"
  ruuniv-server:
    image: ruuniv-server
    container_name: ruuniv-server
    build: .
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Seoul
    env_file:
      - .env
    depends_on:
      - redis-server
