/**
 * Produce
 */

export const KAFKA_TOPIC_COLLECT_STATISTICS = 'COLLECT_STATISTICS';

export const KAFKA_TOPIC_ROLLBACK_DELETE_API_KEY = 'ROLLBACK_DELETE_API_KEY';
export const KAFKA_TOPIC_ROLLBACK_CREATE_API_KEY = 'ROLLBACK_CREATE_API_KEY';

/**
 * Consume
 */

export const KAFKA_TOPIC_CREATE_API_KEY = 'CREATE_API_KEY';
export const KAFKA_TOPIC_DELETE_API_KEY = 'DELETE_API_KEY';
