name: CD_PROD

on:
  workflow_dispatch:
  push: 
    branches:
      - main
  
permissions: write-all #테스트 결과 작성을 위해 쓰기권한 추가

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Docker build & Push
        run: |
          docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}/ruuniv-verification-server .
          docker push ${{ secrets.DOCKER_REPO }}/ruuniv-verification-server
      - name: Deploy to Prod
        uses: appleboy/ssh-action@master
        id: deploy-prod
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
             cd ./project
             sudo docker stop ruuniv-verification-server
             sudo docker rm ruuniv-verification-server
             sudo docker rmi $(sudo docker images -q) 
             sudo docker pull ${{ secrets.DOCKER_REPO }}/ruuniv-verification-server
             sudo docker run -i -t --env-file ./verification.env -p 3000:3000 -d --name ruuniv-verification-server ${{ secrets.DOCKER_REPO }}/ruuniv-verification-server:latest
